# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-12 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20190103_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pubdate',
            field=models.DateField(verbose_name='date published'),
        ),
    ]
